import type { Product, Review, Story, OutfitSuggestion } from '@/types';

// ─── Mock Products ────────────────────────────────────────────────────────────
export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Velvet Midnight Blazer',
    brand: 'ZARA',
    price: 129,
    originalPrice: 189,
    images: [
      'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&q=80',
      'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600&q=80',
      'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&q=80',
    ],
    category: 'outerwear',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: [{ name: 'Midnight Black', hex: '#1a1a1a' }, { name: 'Deep Navy', hex: '#1B2A4A' }],
    rating: 4.8,
    reviewCount: 234,
    description: 'A statement-making velvet blazer with a relaxed fit and peak lapels. Perfect for evening events or styling over a graphic tee for an elevated casual look.',
    material: '78% Polyester, 22% Viscose',
    tags: ['blazer', 'formal', 'evening', 'velvet', 'trending'],
    isNew: false,
    isTrending: true,
    stockCount: 12,
  },
  {
    id: 'p2',
    name: 'Silk Wrap Midi Dress',
    brand: 'Reformation',
    price: 248,
    images: [
      'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600&q=80',
      'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600&q=80',
    ],
    category: 'dresses',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: [{ name: 'Dusty Rose', hex: '#C9A0A0' }, { name: 'Sage', hex: '#8B9E7E' }, { name: 'Ivory', hex: '#F5F0E8' }],
    rating: 4.9,
    reviewCount: 512,
    description: 'Luxurious silk-blend wrap dress with a flattering V-neckline and adjustable tie waist. Effortlessly transitions from day to night.',
    material: '95% Silk, 5% Elastane',
    tags: ['dress', 'silk', 'midi', 'romantic', 'date-night'],
    isNew: true,
    isTrending: true,
    stockCount: 8,
  },
  {
    id: 'p3',
    name: 'High-Rise Sculpt Jeans',
    brand: "Levi's",
    price: 98,
    originalPrice: 128,
    images: [
      'https://images.unsplash.com/photo-1542272604-787c3835535d?w=600&q=80',
      'https://images.unsplash.com/photo-1604176354204-9268737828e4?w=600&q=80',
    ],
    category: 'bottoms',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: [{ name: 'Indigo Wash', hex: '#3D4F6E' }, { name: 'Black Rinse', hex: '#1C1C1E' }],
    rating: 4.7,
    reviewCount: 1203,
    description: 'Signature high-rise jeans crafted with our sculpt denim technology. Stretchy, comfortable and incredibly flattering.',
    material: '92% Cotton, 6% Polyester, 2% Elastane',
    tags: ['jeans', 'denim', 'casual', 'everyday'],
    isNew: false,
    isTrending: false,
    stockCount: 45,
  },
  {
    id: 'p4',
    name: 'Cashmere Oversized Crew',
    brand: 'COS',
    price: 195,
    images: [
      'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=600&q=80',
      'https://images.unsplash.com/photo-1576871337622-98d48d1cf531?w=600&q=80',
    ],
    category: 'tops',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: [{ name: 'Oatmeal', hex: '#C4B49A' }, { name: 'Charcoal', hex: '#4A4A4A' }, { name: 'Dusty Pink', hex: '#D4A0A0' }],
    rating: 4.9,
    reviewCount: 389,
    description: 'Pure cashmere crewneck with an oversized, relaxed silhouette. Incredibly soft to the touch with a timeless minimalist aesthetic.',
    material: '100% Cashmere',
    tags: ['cashmere', 'sweater', 'minimalist', 'luxury', 'cozy'],
    isNew: true,
    isTrending: false,
    stockCount: 24,
  },
  {
    id: 'p5',
    name: 'Strappy Block Heel Mules',
    brand: 'Steve Madden',
    price: 119,
    originalPrice: 149,
    images: [
      'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600&q=80',
      'https://images.unsplash.com/photo-1515347619252-60a4bf4fff4f?w=600&q=80',
    ],
    category: 'shoes',
    sizes: ['6', '7', '8', '9', '10'],
    colors: [{ name: 'Nude', hex: '#D4A574' }, { name: 'Black', hex: '#1a1a1a' }, { name: 'White', hex: '#F5F5F5' }],
    rating: 4.5,
    reviewCount: 678,
    description: 'Chic strappy mules featuring a comfortable block heel. Versatile enough to pair with everything from denim to maxi dresses.',
    tags: ['shoes', 'heels', 'mules', 'versatile'],
    isNew: false,
    isTrending: true,
    stockCount: 33,
  },
  {
    id: 'p6',
    name: 'Asymmetric Hem Blazer Dress',
    brand: 'ASOS Design',
    price: 85,
    images: [
      'https://images.unsplash.com/photo-1539008835657-9e8e9680c956?w=600&q=80',
      'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&q=80',
    ],
    category: 'dresses',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: [{ name: 'Camel', hex: '#C19A6B' }, { name: 'Black', hex: '#1a1a1a' }],
    rating: 4.6,
    reviewCount: 445,
    description: 'A structural blazer-dress hybrid with an asymmetric hemline. Power dressing reinvented for the modern woman.',
    material: '65% Polyester, 35% Viscose',
    tags: ['dress', 'blazer', 'formal', 'office', 'power-dressing'],
    isNew: true,
    isTrending: true,
    stockCount: 18,
  },
  {
    id: 'p7',
    name: 'Linen Wide-Leg Trousers',
    brand: 'H&M',
    price: 49,
    images: [
      'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600&q=80',
      'https://images.unsplash.com/photo-1553754538-466add009c05?w=600&q=80',
    ],
    category: 'bottoms',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: [{ name: 'Natural Linen', hex: '#C9A97A' }, { name: 'White', hex: '#F5F5F5' }, { name: 'Sage Green', hex: '#8DAA8B' }],
    rating: 4.4,
    reviewCount: 892,
    description: 'Breezy linen wide-leg trousers with a high waist and flowing silhouette. Sustainable summer staple.',
    material: '100% Linen',
    tags: ['trousers', 'linen', 'casual', 'summer', 'sustainable'],
    isNew: false,
    isTrending: false,
    stockCount: 67,
  },
  {
    id: 'p8',
    name: 'Leather Crossbody Quilted Bag',
    brand: 'Michael Kors',
    price: 348,
    originalPrice: 428,
    images: [
      'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&q=80',
      'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600&q=80',
    ],
    category: 'accessories',
    sizes: ['S'],
    colors: [{ name: 'Black', hex: '#1a1a1a' }, { name: 'Cognac', hex: '#A0522D' }, { name: 'Blush', hex: '#E8A0A0' }],
    rating: 4.7,
    reviewCount: 234,
    description: 'Quilted leather crossbody bag with gold-tone chain strap. Classic luxury at an accessible price point.',
    material: 'Genuine Leather',
    tags: ['bag', 'crossbody', 'leather', 'luxury', 'accessories'],
    isNew: false,
    isTrending: true,
    stockCount: 15,
  },
  {
    id: 'p9',
    name: 'Ribbed Bodycon Mini Dress',
    brand: 'PrettyLittleThing',
    price: 38,
    images: [
      'https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=600&q=80',
      'https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=600&q=80',
    ],
    category: 'dresses',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: [{ name: 'Hot Pink', hex: '#FF69B4' }, { name: 'Red', hex: '#CC2936' }, { name: 'Black', hex: '#1a1a1a' }],
    rating: 4.3,
    reviewCount: 1567,
    description: 'A form-fitting ribbed knit mini dress that hugs every curve. Your ultimate going-out essential.',
    material: '95% Polyester, 5% Elastane',
    tags: ['dress', 'mini', 'bodycon', 'party', 'night-out'],
    isNew: false,
    isTrending: true,
    stockCount: 78,
  },
  {
    id: 'p10',
    name: 'Oversized Leather Moto Jacket',
    brand: 'AllSaints',
    price: 398,
    originalPrice: 498,
    images: [
      'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&q=80',
      'https://images.unsplash.com/photo-1563682267-a7cedc97e8d3?w=600&q=80',
    ],
    category: 'outerwear',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: [{ name: 'Black', hex: '#1a1a1a' }, { name: 'Biker Brown', hex: '#6B3A1F' }],
    rating: 4.9,
    reviewCount: 678,
    description: 'Iconic biker jacket crafted from premium lamb leather. The ultimate investment piece that only gets better with age.',
    material: '100% Genuine Lamb Leather',
    tags: ['jacket', 'leather', 'moto', 'streetwear', 'iconic'],
    isNew: false,
    isTrending: true,
    stockCount: 9,
  },
  {
    id: 'p11',
    name: 'Floral Chiffon Maxi Skirt',
    brand: 'Free People',
    price: 128,
    images: [
      'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=600&q=80',
      'https://images.unsplash.com/photo-1619086303291-0ef7699e4b31?w=600&q=80',
    ],
    category: 'bottoms',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: [{ name: 'Meadow Floral', hex: '#8B9E7E' }, { name: 'Desert Floral', hex: '#C4A882' }],
    rating: 4.6,
    reviewCount: 334,
    description: 'Dreamy floral chiffon maxi skirt with an elastic waistband and flowing movement. Effortlessly bohemian.',
    material: '100% Polyester Chiffon',
    tags: ['skirt', 'maxi', 'floral', 'bohemian', 'romantic'],
    isNew: true,
    isTrending: false,
    stockCount: 22,
  },
  {
    id: 'p12',
    name: 'Seamless Sculpt Leggings',
    brand: 'Lululemon',
    price: 138,
    images: [
      'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=600&q=80',
      'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80',
    ],
    category: 'activewear',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: [{ name: 'Black', hex: '#1a1a1a' }, { name: 'Navy', hex: '#1B2A4A' }, { name: 'Mauve', hex: '#9B7E8C' }],
    rating: 4.8,
    reviewCount: 2341,
    description: 'Our best-selling Align leggings reimagined with a seamless knit for zero-distraction comfort during any workout.',
    material: '81% Nylon, 19% Lycra',
    tags: ['leggings', 'activewear', 'yoga', 'workout', 'comfort'],
    isNew: false,
    isTrending: true,
    stockCount: 89,
  },
];

// ─── Mock Stories ─────────────────────────────────────────────────────────────
export const MOCK_STORIES: Story[] = [
  { id: 's1', username: 'sophia.m', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&q=80', image: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=600&q=80', hasNew: true },
  { id: 's2', username: 'aria.styles', avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&q=80', image: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=600&q=80', hasNew: true },
  { id: 's3', username: 'zoe.k', avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&q=80', image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&q=80', hasNew: false },
  { id: 's4', username: 'nova.fashion', avatar: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=150&q=80', image: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=600&q=80', hasNew: true },
  { id: 's5', username: 'ella.v', avatar: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=150&q=80', image: 'https://images.unsplash.com/photo-1539008835657-9e8e9680c956?w=600&q=80', hasNew: false },
  { id: 's6', username: 'mia.luxe', avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&q=80', image: 'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=600&q=80', hasNew: true },
];

// ─── Mock Reviews ─────────────────────────────────────────────────────────────
export const MOCK_REVIEWS: Review[] = [
  {
    id: 'r1',
    userId: 'u1',
    username: 'Emily R.',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&q=80',
    rating: 5,
    comment: 'Absolutely obsessed with this piece! The quality exceeded my expectations and it fits like a dream. Got so many compliments at the event.',
    createdAt: new Date('2024-11-15'),
    helpful: 47,
  },
  {
    id: 'r2',
    userId: 'u2',
    username: 'Jasmine K.',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&q=80',
    rating: 4,
    comment: 'Beautiful piece, very true to size. Shipping was fast. Only reason for 4 stars is the color is slightly different from photos — more muted IRL but still stunning.',
    createdAt: new Date('2024-11-08'),
    helpful: 31,
  },
  {
    id: 'r3',
    userId: 'u3',
    username: 'Sofia M.',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=100&q=80',
    rating: 5,
    comment: 'This is my third purchase from this brand and they never disappoint. The fabric quality is incredible and it photographs beautifully.',
    createdAt: new Date('2024-10-29'),
    helpful: 89,
  },
  {
    id: 'r4',
    userId: 'u4',
    username: 'Priya N.',
    avatar: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=100&q=80',
    rating: 4,
    comment: 'Great fit, runs slightly large so size down if you are between sizes. Material feels premium and construction looks durable.',
    createdAt: new Date('2024-10-20'),
    helpful: 24,
  },
];

// ─── Brands ───────────────────────────────────────────────────────────────────
export const BRANDS = ['ZARA', 'Reformation', "Levi's", 'COS', 'Steve Madden', 'ASOS', 'H&M', 'Michael Kors', 'AllSaints', 'Free People', 'Lululemon', 'PrettyLittleThing', 'Mango', 'Topshop', 'Urban Outfitters'];

// ─── Categories ───────────────────────────────────────────────────────────────
export const CATEGORIES = [
  { id: 'tops', label: 'Tops', icon: '👕', emoji: '👚' },
  { id: 'dresses', label: 'Dresses', icon: '👗', emoji: '👗' },
  { id: 'bottoms', label: 'Bottoms', icon: '👖', emoji: '👖' },
  { id: 'outerwear', label: 'Outerwear', icon: '🧥', emoji: '🧥' },
  { id: 'shoes', label: 'Shoes', icon: '👠', emoji: '👠' },
  { id: 'accessories', label: 'Accessories', icon: '👜', emoji: '👜' },
  { id: 'activewear', label: 'Active', icon: '🏃', emoji: '🏋️' },
  { id: 'formal', label: 'Formal', icon: '🎩', emoji: '💼' },
];

// ─── Style Tips ───────────────────────────────────────────────────────────────
export const STYLE_TIPS = [
  { id: 'st1', tip: 'Layer a structured blazer over your favorite slip dress for an effortlessly chic look that transitions day to night.', category: 'Layering' },
  { id: 'st2', tip: 'Monochromatic outfits in neutral tones create an instantly elevated, designer-esque aesthetic without the price tag.', category: 'Color Theory' },
  { id: 'st3', tip: 'Invest in one statement accessory — a bold bag or sculptural earrings — to transform any basic outfit into something memorable.', category: 'Accessories' },
  { id: 'st4', tip: 'The "French tuck" (loosely tucking just the front of your shirt into pants) adds instant polish to any casual look.', category: 'Styling Trick' },
  { id: 'st5', tip: 'Contrast textures for depth — pair something fluid and soft with something structured and sharp for a dynamic silhouette.', category: 'Texture Play' },
];

// ─── Outfit Suggestions ───────────────────────────────────────────────────────
export const MOCK_OUTFIT_SUGGESTIONS: OutfitSuggestion[] = [
  {
    id: 'o1',
    name: 'Evening Elegance',
    products: [MOCK_PRODUCTS[0], MOCK_PRODUCTS[1], MOCK_PRODUCTS[7]],
    occasion: 'Date Night',
  },
  {
    id: 'o2',
    name: 'Casual Chic',
    products: [MOCK_PRODUCTS[3], MOCK_PRODUCTS[2], MOCK_PRODUCTS[4]],
    occasion: 'Weekend Brunch',
  },
  {
    id: 'o3',
    name: 'Power Move',
    products: [MOCK_PRODUCTS[5], MOCK_PRODUCTS[4], MOCK_PRODUCTS[7]],
    occasion: 'Office Glam',
  },
];
