import React, { useEffect, useState } from 'react';
import {
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  ActivityIndicator,
} from 'react-native';
import Animated, {
  useSharedValue,
  useAnimatedStyle,
  withSpring,
  withTiming,
  withDelay,
} from 'react-native-reanimated';
import { Ionicons } from '@expo/vector-icons';
import { COLORS, FONTS, FONT_SIZES, RADIUS, SPACING, SHADOWS } from '@/constants/theme';
import { STYLE_TIPS } from '@/constants/mockData';

export function StyleTipCard() {
  const [tipIndex, setTipIndex] = useState(0);
  const opacity = useSharedValue(0);
  const translateY = useSharedValue(20);
  const scale = useSharedValue(0.95);

  const tip = STYLE_TIPS[tipIndex % STYLE_TIPS.length];

  useEffect(() => {
    opacity.value = withDelay(300, withTiming(1, { duration: 600 }));
    translateY.value = withDelay(300, withSpring(0, { damping: 15, stiffness: 120 }));
    scale.value = withDelay(300, withSpring(1, { damping: 15, stiffness: 120 }));
  }, [tipIndex]);

  const animStyle = useAnimatedStyle(() => ({
    opacity: opacity.value,
    transform: [{ translateY: translateY.value }, { scale: scale.value }],
  }));

  const handleRefresh = () => {
    opacity.value = withTiming(0, { duration: 200 });
    translateY.value = withTiming(-10, { duration: 200 });
    setTimeout(() => {
      setTipIndex((i) => i + 1);
      translateY.value = 20;
      scale.value = 0.95;
    }, 220);
  };

  return (
    <Animated.View style={[styles.card, animStyle]}>
      <View style={styles.header}>
        <View style={styles.aiTag}>
          <Ionicons name="sparkles" size={12} color={COLORS.primary} />
          <Text style={styles.aiLabel}>AI Style Tip</Text>
        </View>
        <TouchableOpacity onPress={handleRefresh} hitSlop={{ top: 8, right: 8, bottom: 8, left: 8 }}>
          <Ionicons name="refresh" size={18} color={COLORS.muted} />
        </TouchableOpacity>
      </View>

      <View style={styles.categoryTag}>
        <Text style={styles.categoryText}>{tip.category}</Text>
      </View>

      <Text style={styles.tipText}>{tip.tip}</Text>

      <View style={styles.footer}>
        <Text style={styles.footerText}>Generated by Aria, your AI stylist</Text>
        <Ionicons name="arrow-forward" size={14} color={COLORS.primary} />
      </View>
    </Animated.View>
  );
}

const styles = StyleSheet.create({
  card: {
    backgroundColor: COLORS.surface,
    borderRadius: RADIUS.xl,
    padding: SPACING.lg,
    borderWidth: 1,
    borderColor: `${COLORS.primary}30`,
    marginHorizontal: SPACING.base,
    ...SHADOWS.primary,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  aiTag: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: `${COLORS.primary}18`,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: RADIUS.full,
  },
  aiLabel: {
    fontSize: FONT_SIZES.xs,
    color: COLORS.primary,
    fontFamily: FONTS.semiBold,
    letterSpacing: 0.3,
  },
  categoryTag: {
    backgroundColor: COLORS.surface2,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: RADIUS.sm,
    alignSelf: 'flex-start',
    marginBottom: 10,
  },
  categoryText: {
    fontSize: FONT_SIZES.xs,
    color: COLORS.muted,
    fontFamily: FONTS.medium,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  tipText: {
    fontSize: FONT_SIZES.base,
    color: COLORS.foreground,
    fontFamily: FONTS.regular,
    lineHeight: 23,
    marginBottom: 14,
  },
  footer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
    paddingTop: 10,
  },
  footerText: {
    fontSize: FONT_SIZES.xs,
    color: COLORS.muted,
    fontFamily: FONTS.regular,
  },
});
